#!/usr/bin/env python3
"""
Add/refresh two cheap-insurance SEO tags in <head> on every real content
page: a canonical URL and a standard <meta name="description">.

Why: the site already carries og:description/twitter:description (added
in a prior pass) but no plain <meta name="description"> — the tag Google's
organic snippet actually prefers — and no canonical tags at all, which is
free protection against trailing-slash/parameter/www-vs-apex duplicates.

Source of truth: the existing og:description content on each page (never
invents new copy) and the page's own path (for the canonical URL).

Injects between clearly marked comment delimiters, idempotent — safe to
re-run any time a page's og:description changes.

Deliberately excludes: 404.html (left as-is per project decision),
googlebc8928ca4194ad24.html (a Search Console verification stub, not a
content page), and anything outside the site (e.g. `from webflow/`,
gitignored reference export).

Usage:
  python3 scripts/add_seo_tags.py              # process every page
  python3 scripts/add_seo_tags.py --only PATH  # process a single page,
                                                 # e.g. recipe-pages/pizza.html
  python3 scripts/add_seo_tags.py --check       # report only, write nothing
"""
import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SITE_URL = "https://sweetsalty.info"

BEGIN_MARKER = "<!-- BEGIN SEO TAGS (auto-generated by scripts/add_seo_tags.py — do not edit by hand) -->"
END_MARKER = "<!-- END SEO TAGS -->"

EXCLUDE = {"404.html", "googlebc8928ca4194ad24.html"}


def discover_pages():
    pages = []
    for pattern in ("*.html", "recipe-pages/*.html", "collection-pages/*.html"):
        for p in sorted(ROOT.glob(pattern)):
            rel = p.relative_to(ROOT).as_posix()
            if rel in EXCLUDE:
                continue
            pages.append(rel)
    return pages


def canonical_url(rel_path):
    # The homepage canonicalizes to the clean root URL, not /index.html —
    # cheap insurance against a duplicate being indexed under both forms.
    if rel_path == "index.html":
        return f"{SITE_URL}/"
    return f"{SITE_URL}/{rel_path}"


def build_block(rel_path, html):
    m = re.search(r'<meta property="og:description" content="(.*?)">', html)
    if not m:
        return None, f"no og:description found on {rel_path} to source the meta description from"
    description = m.group(1)
    canonical = canonical_url(rel_path)
    block = (
        f"{BEGIN_MARKER}\n"
        f'<link rel="canonical" href="{canonical}">\n'
        f'<meta name="description" content="{description}">\n'
        f"{END_MARKER}"
    )
    return block, None


def inject(html, block):
    pattern = re.compile(re.escape(BEGIN_MARKER) + r".*?" + re.escape(END_MARKER), re.DOTALL)
    if pattern.search(html):
        return pattern.sub(block, html)
    # Insert right after <title>...</title> — the conventional spot for
    # canonical/description, ahead of the OG/Twitter block. A function
    # replacement avoids re.sub's backslash-escape handling in `block`.
    new_html, n = re.subn(r"</title>", lambda m: m.group(0) + "\n" + block, html, count=1)
    if n == 0:
        sys.exit("ERROR: no <title> tag found to anchor insertion")
    return new_html


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--only", help="process a single page by relative path")
    ap.add_argument("--check", action="store_true", help="report only, write nothing")
    args = ap.parse_args()

    pages = discover_pages()
    if args.only:
        pages = [p for p in pages if p == args.only]
        if not pages:
            sys.exit(f"ERROR: '{args.only}' not found among discovered pages")

    written, blocked = [], []
    for rel_path in pages:
        path = ROOT / rel_path
        html = path.read_text(encoding="utf-8")
        block, problem = build_block(rel_path, html)
        if problem:
            blocked.append((rel_path, problem))
            continue
        new_html = inject(html, block)
        if not args.check and new_html != html:
            path.write_text(new_html, encoding="utf-8")
        written.append(rel_path)

    print(f"\n{'Would add' if args.check else 'Added'} canonical + meta description to {len(written)} page(s):")
    for p in written:
        print(f"  ✓ {p}")

    if blocked:
        print(f"\nSkipped {len(blocked)} page(s):")
        for p, problem in blocked:
            print(f"  ✗ {p} — {problem}")
        sys.exit(1)


if __name__ == "__main__":
    main()
