#!/usr/bin/env python3
"""
Add a static, crawlable <noscript><ul> fallback list of recipe links to
all-recipes.html and every collection-pages/*.html page.

Why: those pages build their actual recipe-card grid client-side (see
js/main.js, .recipe-grid[data-tag]) from ALL_RECIPES. That means a crawler
that doesn't execute JS finds almost no static links to the 19 recipe
pages from the listing pages — a real discovery gap. This adds a plain
HTML link list next to the grid, generated from the same ALL_RECIPES /
data-tag filter main.js itself uses, so it can never drift out of sync
with what the grid actually shows.

Wrapped in <noscript> per project decision — invisible to JS-enabled
visitors (who get the real grid), present in the raw HTML for crawlers.

Idempotent — safe to re-run any time a recipe is added/removed/re-tagged.

Usage:
  python3 scripts/generate_static_links.py
"""
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from generate_schema import parse_all_recipes, MAIN_JS  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent

BEGIN_MARKER = "<!-- BEGIN STATIC RECIPE LINKS (auto-generated by scripts/generate_static_links.py — do not edit by hand) -->"
END_MARKER = "<!-- END STATIC RECIPE LINKS -->"

GRID_RE = re.compile(r'<div class="recipe-grid" data-tag="([^"]*)"></div>')


def build_block(recipes, tag, path_prefix):
    matches = recipes if tag == "All" else [r for r in recipes if tag in r["tags"]]
    if not matches:
        return None, f"no ALL_RECIPES entries match data-tag=\"{tag}\""
    items = "\n".join(
        f'    <li><a href="{path_prefix}{r["page"]}">{r["title"]}</a></li>' for r in matches
    )
    block = (
        f"{BEGIN_MARKER}\n"
        f'<noscript>\n'
        f'  <ul class="static-recipe-links">\n'
        f'{items}\n'
        f'  </ul>\n'
        f'</noscript>\n'
        f"{END_MARKER}"
    )
    return block, None


def inject(html, block):
    pattern = re.compile(re.escape(BEGIN_MARKER) + r".*?" + re.escape(END_MARKER), re.DOTALL)
    if pattern.search(html):
        return pattern.sub(block, html)

    def add_after_grid(m):
        return m.group(0) + "\n" + block

    new_html, n = GRID_RE.subn(add_after_grid, html, count=1)
    if n == 0:
        sys.exit("ERROR: no <div class=\"recipe-grid\" data-tag=\"...\"></div> found")
    return new_html


def main():
    recipes = parse_all_recipes(MAIN_JS.read_text(encoding="utf-8"))

    targets = [("all-recipes.html", "")]
    for p in sorted((ROOT / "collection-pages").glob("*.html")):
        targets.append((p.relative_to(ROOT).as_posix(), "../"))

    written, blocked = [], []
    for rel_path, prefix in targets:
        path = ROOT / rel_path
        html = path.read_text(encoding="utf-8")
        m = GRID_RE.search(html)
        if not m:
            blocked.append((rel_path, "no .recipe-grid[data-tag] found"))
            continue
        block, problem = build_block(recipes, m.group(1), prefix)
        if problem:
            blocked.append((rel_path, problem))
            continue
        new_html = inject(html, block)
        if new_html != html:
            path.write_text(new_html, encoding="utf-8")
        written.append(rel_path)

    print(f"\nAdded static link list to {len(written)} page(s):")
    for p in written:
        print(f"  ✓ {p}")

    if blocked:
        print(f"\nSkipped {len(blocked)} page(s):")
        for p, problem in blocked:
            print(f"  ✗ {p} — {problem}")
        sys.exit(1)


if __name__ == "__main__":
    main()
